### ISSUE TITLE
black page

### ISSUE THREAD

**Issue by moradpoor** [koval01/notcoinWeb#32]
hi , i deployed on cloudflare and just see a black page , what is wrong ?

**Comment by koval01** [comment]
Hi, maybe you forgot to add environment variables namely VITE_API_HOST and VITE_CDN_HOST
<img width="1100" alt="image" src="https://github.com/koval01/notcoinWeb/assets/61350874/2deb0358-83f9-4d00-82c8-d8088b4038a3">
